version: '2'
services:
    prometheus:
        image: prom/prometheus:0.18.0
        volumes:
            - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'
    node-exporter:
        image: prom/node-exporter:v1.0.0-rc.1
        ports: 
            - '9100:9100'
    grafana:
            image: grafana/grafana:6.7.4
            environment:
                - GF_SECURITY_ADMIN_PASSWORD=pass
            depends_on:
                - prometheus
            ports:
                - "3000:3000"
